# Generated by Django 4.2.1 on 2023-05-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='PetTbl',
        ),
    ]
