# Generated by Django 4.2.1 on 2023-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0006_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='price',
            field=models.FloatField(default='10'),
        ),
    ]
